<?php

declare(strict_types=1);

use App\Cli\ParserApplication;
use App\Cli\ParserOutputWriter;
use App\Mapping\FieldMapper;
use App\Parsers\ParserFactory;
use App\Seeders\JsonSeeder;
use App\Seeders\ProductDataGenerator;

function seedJsonFile(string $dir, int $count): string
{
    $path = $dir . '/seed.json';
    new JsonSeeder(new ProductDataGenerator())->seed($path, $count);
    return $path;
}

beforeEach(function () {
    $this->tempDir = sys_get_temp_dir() . '/cli_tests_' . uniqid();
    mkdir($this->tempDir);
});

afterEach(function () {
    $files = glob($this->tempDir . '/*');
    foreach ($files as $file) {
        if (is_file($file)) {
            unlink($file);
        }
    }
    rmdir($this->tempDir);
});

test('run with help flag', function () {
    $application = new ParserApplication();

    ob_start();
    $exitCode = $application->run(['parser.php', '--help']);
    $output = ob_get_clean();

    expect($exitCode)->toBe(0)
        ->and($output)->toContain('Usage:')
        ->and($output)->toContain('--file=<path>');
});

test('run with missing file parameter', function () {
    $application = new ParserApplication();

    ob_start();
    $exitCode = $application->run(['parser.php']);
    $output = ob_get_clean();

    expect($exitCode)->toBe(1)
        ->and($output)->toContain('Error: --file parameter is required');
});

test('run with non existent file', function () {
    $application = new ParserApplication();

    ob_start();
    $exitCode = $application->run(['parser.php', '--file=nonexistent.csv']);
    $output = ob_get_clean();

    expect($exitCode)->toBe(1)
        ->and($output)->toContain('Error: File not found');
});

test('run with valid json file generated by seeder', function () {
    $inputFile = seedJsonFile($this->tempDir, 1);

    $application = new ParserApplication(
        new ParserFactory(new FieldMapper()),
        new ParserOutputWriter()
    );

    ob_start();
    $exitCode = $application->run(['parser.php', '--file=' . $inputFile]);
    $output = ob_get_clean();

    expect($exitCode)->toBe(0)
        ->and($output)->toContain('Parsing JSON file:')
        ->and($output)->toContain('Total products processed: 1')
        ->and($output)->toContain('Unique combinations: 1');
});

test('run with valid file and output file generated by seeder', function () {
    $inputFile = seedJsonFile($this->tempDir, 2);
    $outputFile = $this->tempDir . '/output.json';

    $application = new ParserApplication();

    ob_start();
    $exitCode = $application->run([
        'parser.php',
        '--file=' . $inputFile,
        '--unique-combinations=' . $outputFile,
    ]);
    $output = ob_get_clean();

    expect($exitCode)->toBe(0)
        ->and($outputFile)->toBeFile()
        ->and($output)->toContain('Unique combinations written to JSON file:');

    $outputData = json_decode(file_get_contents($outputFile), true, 512, JSON_THROW_ON_ERROR);
    expect($outputData)->toBeArray()
        ->toHaveCount(2)
        ->and($outputData[0]['count'])->toBe(1)
        ->and($outputData[1]['count'])->toBe(1);
});
