<?php

declare(strict_types=1);

use App\Enums\CsvDelimiter;
use App\Mapping\FieldMapper;
use App\Models\Product;
use App\Parsers\CsvParser;

beforeEach(function () {
    $this->tempDir = sys_get_temp_dir() . '/parser_tests_' . uniqid();
    mkdir($this->tempDir);
});

afterEach(function () {
    $files = glob($this->tempDir . '/*');
    foreach ($files as $file) {
        if (is_file($file)) {
            unlink($file);
        }
    }
    rmdir($this->tempDir);
});

test('parse comma separated csv generated by seeder', function () {
    $filePath = seedCsvFile($this->tempDir, 2, CsvDelimiter::COMMA);

    $parser = new CsvParser(new FieldMapper());
    $products = iterator_to_array($parser->parse($filePath));

    expect($products)->toHaveCount(2)
        ->and($products[0])->toBeInstanceOf(Product::class)
        ->and($products[0]->make)->toBe('Apple')
        ->and($products[0]->model)->toBe('Alpha 0')
        ->and($products[0]->colour)->toBe('Red')
        ->and($products[1]->make)->toBe('Samsung')
        ->and($products[1]->model)->toBe('Bravo 1');
});

test('parse tab separated csv generated by seeder', function () {
    $filePath = seedCsvFile($this->tempDir, 2, CsvDelimiter::TAB);

    $parser = new CsvParser(new FieldMapper());
    $products = iterator_to_array($parser->parse($filePath));

    expect($products)->toHaveCount(2)
        ->and($products[0]->make)->toBe('Apple')
        ->and($products[1]->make)->toBe('Samsung');
});

test('parse uses generator for memory efficiency with seeded data', function () {
    $filePath = seedCsvFile($this->tempDir, 100, CsvDelimiter::COMMA);

    $parser = new CsvParser(new FieldMapper());
    $generator = $parser->parse($filePath);

    expect($generator)->toBeInstanceOf(Generator::class);

    $count = 0;
    foreach ($generator as $product) {
        $count++;
        if ($count === 10) {
            break;
        }
    }

    expect($count)->toBe(10);
});

test('parse throws exception for missing required field', function () {
    $csvContent = <<<CSV
brand_name,colour_name
Apple,Blue
CSV;

    $filePath = $this->tempDir . '/invalid.csv';
    file_put_contents($filePath, $csvContent);

    $parser = new CsvParser(new FieldMapper());

    expect(fn () => iterator_to_array($parser->parse($filePath)))
        ->toThrow(RuntimeException::class, "Required field 'model' is missing or empty");
});

test('parse handles empty lines', function () {
    $csvContent = "brand_name,model_name\nApple,iPhone 12\n\nSamsung,Galaxy S21";

    $filePath = $this->tempDir . '/empty_lines.csv';
    file_put_contents($filePath, $csvContent);

    $parser = new CsvParser(new FieldMapper());
    $products = iterator_to_array($parser->parse($filePath));

    expect($products)->toHaveCount(2);
});
