<?php

declare(strict_types=1);

use App\Mapping\FieldMapper;
use App\Models\Product;
use App\Parsers\JsonParser;
use App\Seeders\JsonSeeder;
use App\Seeders\NdjsonSeeder;
use App\Seeders\ProductDataGenerator;

function seedJsonFile(string $dir, int $count): string
{
    $path = $dir . '/seed.json';
    new JsonSeeder(new ProductDataGenerator())->seed($path, $count);
    return $path;
}

function seedNdjsonFile(string $dir, int $count): string
{
    $path = $dir . '/seed.ndjson';
    new NdjsonSeeder(new ProductDataGenerator())->seed($path, $count);
    return $path;
}

beforeEach(function () {
    $this->tempDir = sys_get_temp_dir() . '/parser_tests_' . uniqid();
    mkdir($this->tempDir);
});

afterEach(function () {
    $files = glob($this->tempDir . '/*');
    foreach ($files as $file) {
        if (is_file($file)) {
            unlink($file);
        }
    }
    rmdir($this->tempDir);
});

test('parse json direct array generated by seeder', function () {
    $filePath = seedJsonFile($this->tempDir, 2);

    $parser = new JsonParser(new FieldMapper());
    $products = iterator_to_array($parser->parse($filePath));

    expect($products)->toHaveCount(2)
        ->and($products[0])->toBeInstanceOf(Product::class)
        ->and($products[0]->make)->toBe('Apple')
        ->and($products[0]->model)->toBe('Alpha 0')
        ->and($products[1]->make)->toBe('Samsung');
});

test('parse json single object using seeded data', function () {
    $arrayPath = seedJsonFile($this->tempDir, 1);
    $arrayData = json_decode(file_get_contents($arrayPath), true, 512, JSON_THROW_ON_ERROR);

    $objectPath = $this->tempDir . '/single.json';
    file_put_contents($objectPath, json_encode($arrayData[0], JSON_THROW_ON_ERROR));

    $parser = new JsonParser(new FieldMapper());
    $products = iterator_to_array($parser->parse($objectPath));

    expect($products)->toHaveCount(1)
        ->and($products[0]->make)->toBe('Apple')
        ->and($products[0]->model)->toBe('Alpha 0');
});

test('parse ndjson format generated by seeder', function () {
    $filePath = seedNdjsonFile($this->tempDir, 2);

    $parser = new JsonParser(new FieldMapper());
    $products = iterator_to_array($parser->parse($filePath));

    expect($products)->toHaveCount(2)
        ->and($products[0]->make)->toBe('Apple')
        ->and($products[1]->make)->toBe('Samsung');
});

test('parse throws exception for invalid json', function () {
    $filePath = $this->tempDir . '/invalid.json';
    file_put_contents($filePath, '{invalid json}');

    $parser = new JsonParser(new FieldMapper());

    expect(fn () => iterator_to_array($parser->parse($filePath)))
        ->toThrow(RuntimeException::class, 'Invalid JSON');
});

test('parse throws exception for missing required field', function () {
    $jsonContent = json_encode([
        ['brand_name' => 'Apple'],
    ]);

    $filePath = $this->tempDir . '/missing_model.json';
    file_put_contents($filePath, $jsonContent);

    $parser = new JsonParser(new FieldMapper());

    expect(fn () => iterator_to_array($parser->parse($filePath)))
        ->toThrow(RuntimeException::class, "Required field 'model' is missing or empty");
});
