<?php

declare(strict_types=1);

use App\Mapping\FieldMapper;
use App\Models\Product;
use App\Parsers\XmlParser;

beforeEach(function () {
    $this->tempDir = sys_get_temp_dir() . '/parser_tests_' . uniqid();
    mkdir($this->tempDir);
});

afterEach(function () {
    $files = glob($this->tempDir . '/*');
    foreach ($files as $file) {
        if (is_file($file)) {
            unlink($file);
        }
    }
    rmdir($this->tempDir);
});

test('parse xml generated by seeder', function () {
    $filePath = seedXmlFile($this->tempDir, 2);

    $parser = new XmlParser(new FieldMapper());
    $products = iterator_to_array($parser->parse($filePath));

    expect($products)->toHaveCount(2)
        ->and($products[0])->toBeInstanceOf(Product::class)
        ->and($products[0]->make)->toBe('Apple')
        ->and($products[0]->model)->toBe('Alpha 0')
        ->and($products[0]->colour)->toBe('Red')
        ->and($products[1]->make)->toBe('Samsung');
});

test('parse xml with attributes', function () {
    $xmlContent = <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<products>
    <product brand_name="OnePlus" model_name="9 Pro">
        <colour_name>Silver</colour_name>
    </product>
</products>
XML;

    $filePath = $this->tempDir . '/with_attributes.xml';
    file_put_contents($filePath, $xmlContent);

    $parser = new XmlParser(new FieldMapper());
    $products = iterator_to_array($parser->parse($filePath));

    expect($products)->toHaveCount(1)
        ->and($products[0]->make)->toBe('OnePlus')
        ->and($products[0]->model)->toBe('9 Pro')
        ->and($products[0]->colour)->toBe('Silver');
});

test('parse throws exception for invalid xml', function () {
    $filePath = $this->tempDir . '/invalid.xml';
    file_put_contents($filePath, '<invalid xml>');

    $parser = new XmlParser(new FieldMapper());

    expect(fn () => iterator_to_array($parser->parse($filePath)))
        ->toThrow(RuntimeException::class, 'Failed to parse XML');
});

test('parse throws exception for missing required field', function () {
    $xmlContent = <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<products>
    <product>
        <brand_name>Apple</brand_name>
    </product>
</products>
XML;

    $filePath = $this->tempDir . '/missing_model.xml';
    file_put_contents($filePath, $xmlContent);

    $parser = new XmlParser(new FieldMapper());

    expect(fn () => iterator_to_array($parser->parse($filePath)))
        ->toThrow(RuntimeException::class, "Required field 'model' is missing or empty");
});
